### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [karimnaaji/voxelizer#2]
I would like to point out that an identifier like "[`vx__map_to_voxel`](https://github.com/karimnaaji/voxelizer/blob/fb6377d1e561ec4f961db28f47992b08747c2723/voxelizer.h#L278)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by karimnaaji** [comment]
I don't have much more to say than anything said in https://github.com/nothings/stb/issues/277#issuecomment-206475516.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106)?
